name: "TypeScript Test Action"
description: "TypeScript Test Action"
author: "Shane"
branding:
  icon: "type"
  color: "green"

inputs:
  milliseconds:
    description: "Your input description here"
    required: false
    default: "1000"

outputs:
  time:
    description: "Your output description here"

runs:
  using: "node20"
  main: "dist/index.js"
